name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gen-lang-client-0303076515 # Extraído del JSON de la cuenta de servicio
  SERVICE_NAME: impulsopr-tv-apps
  REGION: us-east1

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and Push Container
        run: |-
          docker build \
            --build-arg VITE_GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
            --build-arg VITE_SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            --build-arg VITE_SUPABASE_ANON_KEY="${{ secrets.SUPABASE_ANON_KEY }}" \
            --build-arg VITE_FIREBASE_API_KEY="AIzaSyANqjrgWXBDnhfaR04Nsd5-RL3fmDtrv1Q" \
            --build-arg VITE_FIREBASE_AUTH_DOMAIN="gen-lang-client-0303076515.firebaseapp.com" \
            --build-arg VITE_FIREBASE_PROJECT_ID="gen-lang-client-0303076515" \
            --build-arg VITE_FIREBASE_STORAGE_BUCKET="gen-lang-client-0303076515.firebasestorage.app" \
            --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID="572316843568" \
            --build-arg VITE_FIREBASE_APP_ID="1:572316843568:web:46c84995cbb25c783e77f5" \
            --build-arg VITE_FIREBASE_MEASUREMENT_ID="G-5DSY40ZDHW" \
            -t "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" .
          docker push "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image "gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
